import { normalizeEmail, validatePassword, canManage } from './auth-utils.mjs';
import { buildSingleEliminationPairings } from './draw-utils.mjs';

const cfg=window.SPORTSVN_CONFIG||{};
const root=document.querySelector('#admin-app');
const configured=cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_URL.includes('YOUR_') && !cfg.SUPABASE_ANON_KEY.includes('YOUR_');
const sb=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let session=null, profile=null;
const CONTACT={email:'Nguyenquanghao2505@gmail.com',phone:'0905771177',zalo:['0905771177','0384913999']};
const BANK={owner:'Nguyễn Quang Hảo',bank:'SHB – Chi nhánh Đà Nẵng',account:'0107797979'};
const nav=[['dashboard','Tổng quan'],['tournaments','Giải đấu'],['athletes','Vận động viên'],['organizations','Đơn vị / CLB'],['venues','Đặt sân / địa điểm'],['draw','Bốc thăm'],['matches','Lịch thi đấu'],['results','Kết quả'],['news','Tin tức'],['ai','AI SportsVN'],['billing','Thanh toán']];

function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(text,ok=false){const el=document.querySelector('#toast');if(el){el.textContent=text;el.className='toast show '+(ok?'ok':'');setTimeout(()=>el.className='toast',2500);}}
function login(){root.innerHTML=`<div class="login-wrap"><form id="login" class="login-card"><div class="login-logo">SV</div><h1>SportsVN</h1><p>Trung tâm quản lý giải đấu</p><label>Email<input id="email" type="email" autocomplete="username" required></label><label>Mật khẩu<input id="password" type="password" autocomplete="current-password" required></label><button class="btn primary">ĐĂNG NHẬP</button><div id="err" class="form-error"></div><small>Hỗ trợ: ${CONTACT.email} · ${CONTACT.phone}</small></form></div>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const err=document.querySelector('#err');const email=normalizeEmail(document.querySelector('#email').value);const pass=document.querySelector('#password').value;const check=validatePassword(pass);if(!check.ok){err.textContent=check.message;return;}if(!sb){err.textContent='Chưa cấu hình Supabase trong config.js.';return;}const {error}=await sb.auth.signInWithPassword({email,password:pass});if(error)err.textContent='Email hoặc mật khẩu không chính xác.';};}
async function getProfile(){if(!sb||!session)return null;const {data,error}=await sb.from('profiles').select('id,full_name,phone,role').eq('id',session.user.id).single();if(error)console.error(error);return data;}
function shell(){const key=location.hash.slice(1)||'dashboard';root.innerHTML=`<div id="toast" class="toast"></div><div class="admin-layout"><aside class="sidebar"><div class="admin-brand"><b>SV</b><strong>SPORTSVN</strong><small>Trung tâm điều hành</small></div><div class="side-nav">${nav.map(([k,v])=>`<a href="#${k}" class="${key===k?'active':''}">${v}</a>`).join('')}</div><div class="contact-mini">${escapeHtml(CONTACT.email)}<br>${CONTACT.phone}</div><button id="logout" class="logout">Đăng xuất</button></aside><section class="admin-main"><header class="admin-head"><div><span>SPORTSVN</span><h1>${nav.find(x=>x[0]===key)?.[1]||'Tổng quan'}</h1></div><div class="user-pill">${escapeHtml(profile?.full_name||session.user.email)} · ${escapeHtml(profile?.role||'manager')}</div></header><div id="view"></div></section></div>`;document.querySelector('#logout').onclick=()=>sb.auth.signOut();renderView(key);}
async function renderView(key){const v=document.querySelector('#view');if(!v)return;if(key==='dashboard')return dashboard(v);if(key==='tournaments')return tournaments(v);if(key==='billing')return billing(v);const titles={athletes:'Vận động viên',organizations:'Đơn vị / CLB',venues:'Đặt sân / địa điểm',draw:'Bốc thăm',matches:'Lịch thi đấu',results:'Kết quả',news:'Tin tức',ai:'AI SportsVN'};v.innerHTML=`<div class="admin-panel"><div class="panel-head"><h2>${titles[key]||'Tính năng'}</h2></div><div class="empty">Module <b>${titles[key]||key}</b> đã sẵn sàng để kết nối dữ liệu. Các module sẽ dùng cùng quyền sở hữu giải đấu của tài khoản này.</div></div>`;}
async function dashboard(v){let counts={t:0,a:0,o:0,v:0};if(sb){const tables=['tournaments','athletes','organizations','venues'];const rs=await Promise.all(tables.map(t=>sb.from(t).select('id',{count:'exact',head:true})));counts={t:rs[0].count||0,a:rs[1].count||0,o:rs[2].count||0,v:rs[3].count||0};}v.innerHTML=`<div class="admin-cards"><article><span>Giải đấu</span><b>${counts.t}</b></article><article><span>Vận động viên</span><b>${counts.a}</b></article><article><span>Đơn vị / CLB</span><b>${counts.o}</b></article><article><span>Địa điểm</span><b>${counts.v}</b></article></div><div class="admin-panel"><div class="panel-head"><div><h2>Chào mừng đến SportsVN</h2><p>Quản lý giải đấu, bốc thăm, lịch thi đấu và kết quả trên cùng một hệ thống.</p></div><a class="btn primary" href="#tournaments">＋ Tạo giải đấu</a></div><div class="info-grid"><div><b>Liên hệ</b><p>${CONTACT.email}<br>${CONTACT.phone}<br>Zalo: ${CONTACT.zalo.join(' · ')}</p></div><div><b>Thanh toán chuyển khoản</b><p>${BANK.owner}<br>${BANK.bank}<br>STK: <strong>${BANK.account}</strong></p></div></div></div>`;}
async function tournaments(v){if(!canManage(profile)){v.innerHTML='<div class="admin-panel"><h2>Không có quyền</h2><p>Tài khoản hiện tại không có quyền quản lý giải đấu.</p></div>';return;}const {data:rows,error}=await sb.from('tournaments').select('*').order('created_at',{ascending:false});if(error){v.innerHTML=`<div class="admin-panel"><p class="form-error">Không đọc được dữ liệu: ${escapeHtml(error.message)}</p></div>`;return;}v.innerHTML=`<div class="admin-panel"><div class="panel-head"><div><h2>Giải đấu của tôi</h2><p>Tạo và chỉnh sửa trực tiếp trên website.</p></div><button id="newTournament" class="btn primary">＋ Tạo giải đấu</button></div><div class="table-wrap"><table><thead><tr><th>Tên giải</th><th>Môn</th><th>Thời gian</th><th>Trạng thái</th><th></th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><td><strong>${escapeHtml(r.name)}</strong></td><td>${escapeHtml(r.sport)}</td><td>${r.start_date||'—'} → ${r.end_date||'—'}</td><td>${escapeHtml(r.status)}</td><td><button class="linkbtn edit" data-id="${r.id}">Sửa</button> <button class="linkbtn del" data-id="${r.id}">Xóa</button></td></tr>`).join('')||'<tr><td colspan="5">Chưa có giải đấu.</td></tr>'}</tbody></table></div><div id="editor"></div></div>`;document.querySelector('#newTournament').onclick=()=>editor();document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editor((rows||[]).find(x=>x.id===b.dataset.id)));document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm('Xóa giải đấu này?'))return;const {error}=await sb.from('tournaments').delete().eq('id',b.dataset.id);if(error)toast(error.message);else{toast('Đã xóa giải đấu',true);tournaments(v)}});}
function editor(row=null){const e=document.querySelector('#editor');e.innerHTML=`<form id="tourForm" class="editor"><h3>${row?'Chỉnh sửa':'Tạo'} giải đấu</h3><div class="form-grid"><label>Tên giải<input name="name" required value="${escapeHtml(row?.name||'')}"></label><label>Môn thể thao<input name="sport" required value="${escapeHtml(row?.sport||'')}"></label><label>Ngày bắt đầu<input name="start_date" type="date" value="${row?.start_date||''}"></label><label>Ngày kết thúc<input name="end_date" type="date" value="${row?.end_date||''}"></label><label>Trạng thái<select name="status"><option value="draft">Nháp</option><option value="registration">Mở đăng ký</option><option value="running">Đang thi đấu</option><option value="finished">Đã kết thúc</option></select></label><label>Địa điểm<input name="venue_name" value="${escapeHtml(row?.venue_name||'')}"></label></div><label>Mô tả<textarea name="description">${escapeHtml(row?.description||'')}</textarea></label><button class="btn primary">Lưu giải đấu</button> <button type="button" id="cancelEdit" class="btn">Hủy</button></form>`;e.querySelector('#cancelEdit').onclick=()=>e.innerHTML='';e.querySelector('#tourForm').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);const payload=Object.fromEntries(f.entries());payload.owner_id=session.user.id;if(payload.start_date&&payload.end_date&&payload.end_date<payload.start_date)return toast('Ngày kết thúc phải sau ngày bắt đầu.');let q=row?sb.from('tournaments').update(payload).eq('id',row.id):sb.from('tournaments').insert(payload);const {error}=await q;if(error)toast(error.message);else{toast('Đã lưu giải đấu',true);tournaments(document.querySelector('#view'));}};}
function billing(v){v.innerHTML=`<div class="admin-panel"><h2>Thanh toán SportsVN</h2><p>Thông tin chuyển khoản chính thức:</p><div class="bank-card"><b>${BANK.owner}</b><span>${BANK.bank}</span><strong>${BANK.account}</strong><small>Nội dung: SPORTSVN + mã đơn hàng</small></div><p class="muted">Khi triển khai cổng thanh toán tự động, khóa bí mật sẽ được đặt phía máy chủ, không đưa vào GitHub.</p></div>`;}
async function start(){if(!sb)return login();const {data}=await sb.auth.getSession();session=data.session;if(!session)return login();profile=await getProfile();shell();sb.auth.onAuthStateChange(async(_e,s)=>{session=s;if(!session){profile=null;login();}else{profile=await getProfile();shell();}});}
window.addEventListener('hashchange',()=>{if(session)shell()});start();
