import {slugify,buildSingleElimination} from '../core.mjs';
const sb=window.sportsvnSupabase;
const state={session:null,profile:null,page:'dashboard'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fail=(e)=>{throw new Error(e?.message||String(e));};

async function boot(){
 const {data:{session}}=await sb.auth.getSession();
 state.session=session;
 if(!session){showLogin();return;}
 await loadProfile(); showApp(); await render();
 sb.auth.onAuthStateChange((_event,s)=>{state.session=s;if(!s)showLogin();});
}
async function loadProfile(){const {data,error}=await sb.from('profiles').select('*').eq('id',state.session.user.id).maybeSingle();if(error)fail(error);state.profile=data;}
function showLogin(){$('#login').classList.remove('hidden');$('#app').classList.add('hidden');}
function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#user-email').textContent=state.session.user.email||'';}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';try{const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)fail(error);await boot();}catch(err){$('#login-error').textContent=err.message;}});
$('#logout').addEventListener('click',()=>sb.auth.signOut());
$('#menu').addEventListener('click',async e=>{const b=e.target.closest('button[data-page]');if(!b)return;state.page=b.dataset.page;document.querySelectorAll('#menu button').forEach(x=>x.classList.toggle('active',x===b));await render();});

async function count(table){const {count,error}=await sb.from(table).select('*',{count:'exact',head:true});if(error)return 0;return count||0;}
async function render(){const titles={dashboard:'Tổng quan',tournaments:'Giải đấu',organizations:'Đơn vị / CLB',athletes:'Vận động viên',entries:'Đăng ký thi đấu',draw:'Bốc thăm',matches:'Lịch & kết quả',news:'Tin tức',payments:'Thanh toán',account:'Tài khoản'};$('#page-title').textContent=titles[state.page];try{await pages[state.page]();}catch(e){$('#content').innerHTML=`<div class="panel"><b>Lỗi hệ thống</b><p>${esc(e.message)}</p></div>`;}}

const pages={
 dashboard:async()=>{const [t,a,o,m,n]=await Promise.all(['tournaments','athletes','organizations','matches','news'].map(count));$('#content').innerHTML=`<div class="page-grid"><div class="stat"><small>Giải đấu</small><strong>${t}</strong></div><div class="stat"><small>Vận động viên</small><strong>${a}</strong></div><div class="stat"><small>Đơn vị / CLB</small><strong>${o}</strong></div><div class="stat"><small>Trận đấu</small><strong>${m}</strong></div></div><div class="panel"><div class="panel-head"><h2>SportsVN Production</h2></div><p>Đang đăng nhập với tài khoản <b>${esc(state.session.user.email)}</b>.</p><p>Vai trò: <span class="badge">${esc(state.profile?.role||'chưa phân quyền')}</span></p><p>Hệ thống dữ liệu được bảo vệ bằng Supabase Auth + Row Level Security.</p></div>`},
 tournaments:async()=>crudPage({title:'Quản lý giải đấu',table:'tournaments',fields:[['name','Tên giải','text',true],['sport','Môn thể thao','text',true],['discipline','Nội dung','text',false],['start_date','Ngày bắt đầu','date',false],['end_date','Ngày kết thúc','date',false],['venue_name','Địa điểm','text',false],['description','Mô tả','textarea',false],['status','Trạng thái','select',false,['draft','registration','running','finished','archived']],['public_visible','Hiển thị công khai','checkbox',false],['registration_open','Mở đăng ký','checkbox',false]],columns:['name','sport','start_date','status','public_visible'] ,transform:r=>({...r,slug:r.slug||slugify(r.name),owner_id:state.session.user.id})}),
 organizations:async()=>crudPage({title:'Đơn vị / CLB',table:'organizations',fields:[['name','Tên đơn vị','text',true],['short_name','Tên viết tắt','text',false],['contact_name','Người liên hệ','text',false],['phone','Điện thoại','text',false],['email','Email','email',false],['address','Địa chỉ','text',false]],columns:['name','short_name','contact_name','phone'],transform:r=>({...r,owner_id:state.session.user.id})}),
 athletes:async()=>crudPage({title:'Vận động viên',table:'athletes',fields:[['full_name','Họ và tên','text',true],['athlete_code','Mã VĐV','text',false],['birth_date','Ngày sinh','date',false],['gender','Giới tính','text',false],['phone','Điện thoại','text',false],['email','Email','email',false]],columns:['full_name','athlete_code','birth_date','gender'],transform:r=>({...r,owner_id:state.session.user.id})}),
 news:async()=>crudPage({title:'Tin tức',table:'news',fields:[['title','Tiêu đề','text',true],['category','Chuyên mục','text',false],['excerpt','Sapo','textarea',false],['body','Nội dung','textarea',false],['cover_url','Ảnh đại diện URL','url',false],['source_name','Nguồn','text',false],['source_url','Link nguồn','url',false],['status','Trạng thái','select',false,['draft','published','archived']]],columns:['title','category','status','published_at'],transform:r=>({...r,slug:r.slug||slugify(r.title),owner_id:state.session.user.id,published_at:r.status==='published'?(r.published_at||new Date().toISOString()):null})}),
 payments:async()=>crudPage({title:'Thanh toán',table:'payments',readOnly:true,fields:[],columns:['order_code','plan_code','amount','status','provider','created_at']}),
 entries:async()=>{
    const [{data:tournaments,error:te},{data:athletes,error:ae}]=await Promise.all([sb.from('tournaments').select('id,name').order('created_at',{ascending:false}),sb.from('athletes').select('id,full_name').order('full_name')]);if(te)fail(te);if(ae)fail(ae);
    const {data:entries,error}=await sb.from('tournament_entries').select('id,content,approved,athlete:athletes(full_name),tournaments(name)').order('created_at',{ascending:false}).limit(300);if(error)fail(error);
    $('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>Đăng ký thi đấu</h2></div><form id="entry-form" class="form-grid"><label>Giải đấu<select id="entry-tournament">${(tournaments||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label>Vận động viên<select id="entry-athlete">${(athletes||[]).map(x=>`<option value="${x.id}">${esc(x.full_name)}</option>`).join('')}</select></label><label>Nội dung<input id="entry-content" placeholder="Ví dụ: Đơn nam"></label><label>Duyệt<input id="entry-approved" type="checkbox" style="width:auto;display:block;margin-top:12px"></label><div class="full"><button class="btn primary">Thêm đăng ký</button></div></form></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Giải</th><th>VĐV</th><th>Nội dung</th><th>Duyệt</th><th></th></tr></thead><tbody>${(entries||[]).map(x=>`<tr><td>${esc(x.tournaments?.name)}</td><td>${esc(x.athlete?.full_name)}</td><td>${esc(x.content)}</td><td>${x.approved?'Có':'Chưa'}</td><td><button class="btn danger entry-del" data-id="${x.id}">Xóa</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Chưa có đăng ký.</td></tr>'}</tbody></table></div></div>`;
    $('#entry-form').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('tournament_entries').insert({tournament_id:$('#entry-tournament').value,athlete_id:$('#entry-athlete').value,content:$('#entry-content').value||null,approved:$('#entry-approved').checked,organization_id:null});if(error)alert(error.message);else await render();};
    document.querySelectorAll('.entry-del').forEach(b=>b.onclick=async()=>{if(!confirm('Xóa đăng ký này?'))return;const {error}=await sb.from('tournament_entries').delete().eq('id',b.dataset.id);if(error)alert(error.message);else await render();});
  },
 draw:async()=>{
    const {data:tournaments,error:te}=await sb.from('tournaments').select('id,name').order('created_at',{ascending:false});if(te)fail(te);
    $('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>Bốc thăm tự động</h2></div><p>Hệ thống sử dụng các suất đã duyệt, cố gắng tránh cùng đơn vị ở vòng 1, tự tạo BYE và toàn bộ nhánh loại trực tiếp.</p><label>Giải đấu<select id="draw-tournament">${(tournaments||[]).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><div id="draw-info"></div><button id="run-draw" class="btn primary">BỐC THĂM & LƯU NHÁNH</button></div><div id="draw-preview"></div>`;
    const loadEntries=async()=>{const tid=$('#draw-tournament').value;const {data,error}=await sb.from('tournament_entries').select('id,approved,athlete:athletes(id,full_name),team:teams(id,name),organization:organizations(id,name)').eq('tournament_id',tid).eq('approved',true);if(error)fail(error);const entries=(data||[]).map(x=>({id:x.id,name:x.athlete?.full_name||x.team?.name||'Chưa có tên',unit:x.organization?.name||''}));$('#draw-info').innerHTML=`<p><b>${entries.length}</b> suất đã duyệt.</p>`;return entries;};
    await loadEntries();$('#draw-tournament').onchange=loadEntries;
    $('#run-draw').onclick=async()=>{try{const tid=$('#draw-tournament').value;const entries=await loadEntries();if(entries.length<2){alert('Cần ít nhất 2 suất đã duyệt.');return;}const bracket=buildSingleElimination(entries,{avoidSameUnit:true});if(!confirm(`Tạo nhánh ${bracket.size} suất và lưu ${bracket.matches.length} trận?`))return;const {error:del}=await sb.from('matches').delete().eq('tournament_id',tid);if(del)fail(del);const rows=bracket.matches.map(m=>({tournament_id:tid,round_name:m.roundName,round_no:m.roundNo,match_no:m.matchNo,entry_a_id:m.a?.id||null,entry_b_id:m.b?.id||null,status:m.bye?'finished':'scheduled',winner_entry_id:m.bye?m.a?.id:null}));const {data:inserted,error}=await sb.from('matches').insert(rows).select('id,round_no,match_no');if(error)fail(error);$('#draw-preview').innerHTML=`<div class="panel"><h2>Đã lưu nhánh đấu</h2><p>${inserted.length} trận được tạo.</p><div class="table-wrap"><table class="table"><thead><tr><th>Vòng</th><th>Trận</th><th>A</th><th>B</th><th>BYE</th></tr></thead><tbody>${bracket.matches.map(m=>`<tr><td>${esc(m.roundName)}</td><td>${m.matchNo}</td><td>${esc(m.a?.name||'—')}</td><td>${esc(m.b?.name||'—')}</td><td>${m.bye?'Có':'-'}</td></tr>`).join('')}</tbody></table></div></div>`;}catch(e){alert(e.message)}};
  },
 matches:async()=>{const {data,error}=await sb.from('matches').select('id,round_name,round_no,match_no,scheduled_at,score_a,score_b,status,tournaments(name)').order('scheduled_at',{ascending:true,nullsFirst:true}).limit(300);if(error)fail(error);$('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>Lịch & kết quả</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Giải</th><th>Vòng</th><th>Trận</th><th>Thời gian</th><th>Tỷ số</th><th>Trạng thái</th><th></th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.tournaments?.name)}</td><td>${esc(x.round_name)}</td><td>${x.match_no}</td><td>${esc(x.scheduled_at||'')}</td><td><input class="score-a" data-id="${x.id}" value="${x.score_a??''}" style="width:55px"> - <input class="score-b" data-id="${x.id}" value="${x.score_b??''}" style="width:55px"></td><td><select class="match-status" data-id="${x.id}"><option ${x.status==='scheduled'?'selected':''}>scheduled</option><option ${x.status==='live'?'selected':''}>live</option><option ${x.status==='finished'?'selected':''}>finished</option><option ${x.status==='cancelled'?'selected':''}>cancelled</option></select></td><td><button class="btn save-match" data-id="${x.id}">Lưu</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Chưa có trận đấu.</td></tr>'}</tbody></table></div></div>`;document.querySelectorAll('.save-match').forEach(b=>b.onclick=async()=>{const id=b.dataset.id;const a=document.querySelector(`.score-a[data-id="${id}"]`).value;const c=document.querySelector(`.score-b[data-id="${id}"]`).value;const status=document.querySelector(`.match-status[data-id="${id}"]`).value;const {error}=await sb.from('matches').update({score_a:a===''?null:Number(a),score_b:c===''?null:Number(c),status}).eq('id',id);if(error)alert(error.message);else b.textContent='Đã lưu';});},
 account:async()=>{$('#content').innerHTML=`<div class="panel"><h2>Tài khoản</h2><p>Email: <b>${esc(state.session.user.email)}</b></p><p>Vai trò: <span class="badge">${esc(state.profile?.role||'')}</span></p><p>Muốn cấp quyền quản trị hệ thống, tài khoản phải được gán vai trò trong bảng <code>profiles</code> bằng tài khoản có quyền phù hợp.</p></div>`}
};

async function crudPage(opts){
 const {data,error}=await sb.from(opts.table).select('*').order('created_at',{ascending:false}).limit(200);if(error)fail(error);
 const fields=opts.fields||[];
 let form=''; if(!opts.readOnly){form=`<form id="crud-form" class="panel"><div class="form-grid">${fields.map(f=>fieldHtml(f)).join('')}</div><div class="toolbar" style="margin-top:14px"><button class="btn primary">Lưu</button><button type="button" class="btn" id="cancel-edit">Hủy</button></div><input type="hidden" id="edit-id"></form>`;}
 const rows=(data||[]).map(r=>`<tr>${opts.columns.map(c=>`<td>${c==='public_visible'?r[c]?'Có':'Không':esc(r[c])}</td>`).join('')}<td>${opts.readOnly?'':`<div class="actions"><button class="btn edit" data-id="${r.id}">Sửa</button><button class="btn danger del" data-id="${r.id}">Xóa</button></div>`}</td></tr>`).join('');
 $('#content').innerHTML=`<div class="panel-head"><h2>${opts.title}</h2></div>${form}<div class="panel"><div class="table-wrap"><table class="table"><thead><tr>${opts.columns.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Thao tác</th></tr></thead><tbody>${rows||`<tr><td colspan="${opts.columns.length+1}" class="empty">Chưa có dữ liệu.</td></tr>`}</tbody></table></div></div>`;
 if(opts.readOnly)return;
 $('#cancel-edit').onclick=()=>resetForm();
 $('#crud-form').onsubmit=async e=>{e.preventDefault();try{const obj=Object.fromEntries(fields.map(f=>[f[0],readField(f)]));const id=$('#edit-id').value;const payload=opts.transform?opts.transform(obj):obj;let q=id?sb.from(opts.table).update(payload).eq('id',id):sb.from(opts.table).insert(payload);const {error}=await q;if(error)fail(error);await render();}catch(e){alert(e.message)}};
 document.querySelectorAll('.edit').forEach(btn=>btn.onclick=()=>{const r=data.find(x=>x.id===btn.dataset.id);if(!r)return;$('#edit-id').value=r.id;fields.forEach(f=>setField(f,r[f[0]]));window.scrollTo({top:0,behavior:'smooth'});});
 document.querySelectorAll('.del').forEach(btn=>btn.onclick=async()=>{if(!confirm('Xóa bản ghi này?'))return;const {error}=await sb.from(opts.table).delete().eq('id',btn.dataset.id);if(error)alert(error.message);else await render();});
}
function fieldHtml(f){const [name,label,type,required,options]=f;if(type==='textarea')return `<label class="full">${label}<textarea id="f-${name}" ${required?'required':''}></textarea></label>`;if(type==='select')return `<label>${label}<select id="f-${name}">${options.map(o=>`<option value="${o}">${o}</option>`).join('')}</select></label>`;if(type==='checkbox')return `<label>${label}<input id="f-${name}" type="checkbox" style="width:auto;display:block;margin-top:12px"></label>`;return `<label>${label}<input id="f-${name}" type="${type}" ${required?'required':''}></label>`;}
function readField(f){const [name,,type]=f;const el=$(`#f-${name}`);if(type==='checkbox')return el.checked;return el.value||null;}
function setField(f,v){const [name,,type]=f;const el=$(`#f-${name}`);if(!el)return;if(type==='checkbox')el.checked=!!v;else el.value=v??'';}
function resetForm(){if($('#crud-form')){$('#crud-form').reset();$('#edit-id').value='';}}
boot();
