import { slugify, drawFirstRound, hasVenueConflict } from './core.mjs';

const cfg = window.SPORTSVN_CONFIG;
const sb = window.supabase.createClient(cfg.supabaseUrl, cfg.supabasePublishableKey);
const $ = s => document.querySelector(s);
const content = $('#content');
const state = { user:null, view:'dashboard', entrants:[
  {name:'Nguyễn Văn A',unit:'Đà Nẵng'},{name:'Trần Văn B',unit:'Đà Nẵng'},
  {name:'Lê Văn C',unit:'Quảng Nam'},{name:'Phạm Văn D',unit:'Huế'},
  {name:'Hoàng Văn E',unit:'Đà Nẵng'},{name:'Võ Văn F',unit:'Quảng Nam'},
  {name:'Đặng Văn G',unit:'Thanh Hóa'},{name:'Bùi Văn H',unit:'Huế'}
]};

const demo = {
  tournaments:[
    ['Giải Cầu lông Đại hội TDTT TP Đà Nẵng lần X','Cầu lông','16–20/08/2026','Nhà thi đấu Tiên Sơn','Đang diễn ra'],
    ['Giải Bóng rổ trẻ 5x5 U16 Quốc gia 2026','Bóng rổ','24–28/08/2026','Cung ứng dịch vụ sự nghiệp công phường An Hải','Sắp diễn ra'],
    ['Đua thuyền truyền thống mở rộng — Cúp VTV8','Đua thuyền','30/08/2026','Sông Hàn — Đà Nẵng','Sắp diễn ra'],
    ['Pickleball Đại hội TDTT TP Đà Nẵng lần X','Pickleball','27–30/06/2026','Hợp Thành Phát','Đã kết thúc']
  ],
  matches:[['08:00','Cầu lông · Đơn nam','Sân 1','Nguyễn Văn A — Trần Văn B','LIVE'],['09:30','Cầu lông · Đơn nữ','Sân 2','Ngọc Lan — Thu Hà','Sắp diễn ra'],['10:30','Bóng bàn · Đơn nam','Sân 3','Lê C — Phạm D','Sắp diễn ra'],['14:00','Cầu lông · Đôi nam','Sân 1','Đà Nẵng — Quảng Nam','Sắp diễn ra']],
  news:[['Taekwondo','Đà Nẵng: Bế mạc Giải Taekwondo Đại hội TDTT lần thứ X năm 2026','18/08/2026'],['Cầu lông','Những khoảnh khắc ấn tượng ngày thi đấu','17/08/2026'],['Bóng rổ','Lịch thi đấu bóng rổ U16 Quốc gia 2026 chính thức','16/08/2026']]
};

function setMessage(text, ok=false){ const el=$('#loginMessage'); el.textContent=text; el.style.color=ok?'#087b55':'#c73535'; }
async function login(email,password){
  const {data,error}=await sb.auth.signInWithPassword({email,password});
  if(error) throw error; return data.user;
}
async function currentUser(){ const {data:{session}}=await sb.auth.getSession(); return session?.user || null; }
async function signOut(){ await sb.auth.signOut(); state.user=null; $('#app').classList.add('hidden'); $('#login').classList.remove('hidden'); }

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#loginButton');btn.disabled=true;btn.textContent='ĐANG ĐĂNG NHẬP...';setMessage('');try{state.user=await login($('#email').value.trim(),$('#password').value);$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await render();}catch(err){setMessage('Đăng nhập không thành công. Vui lòng kiểm tra email và mật khẩu.');}finally{btn.disabled=false;btn.textContent='ĐĂNG NHẬP';}});
$('#forgot').addEventListener('click',async e=>{e.preventDefault();const email=$('#email').value.trim()||cfg.adminEmail;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:cfg.siteUrl+'/admin/'});setMessage(error?'Không thể gửi email khôi phục. Hãy thử lại sau.':'Đã gửi email khôi phục đến '+email,true);});
$('#hamb').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#nav').addEventListener('click',async e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('open');await render();});

function shell(title,sub,body,actions=''){return `<div class="page-head"><div><h1>${title}</h1><div class="muted">${sub}</div></div><div class="toolbar">${actions}</div></div>${body}`}
function stats(){return `<div class="grid grid-4"><div class="card stat">🏆<b>12</b><span>Giải đang diễn ra</span></div><div class="card stat">♙<b>2.586</b><span>VĐV đăng ký</span></div><div class="card stat">♧<b>356</b><span>Đơn vị / CLB</span></div><div class="card stat">🏅<b>432</b><span>Huy chương</span></div></div>`}
function dashboard(){return shell('Trung tâm điều hành SportsVN','Đăng ký → hồ sơ → bốc thăm → lịch sân → kết quả → truyền thông',`<div class="hero"><div class="hero-banner"><span class="pill green">ĐANG DIỄN RA</span><h2>GIẢI CẦU LÔNG ĐẠI HỘI THỂ DỤC THỂ THAO THÀNH PHỐ ĐÀ NẴNG LẦN THỨ X NĂM 2026</h2><p>16–20/08/2026 · Nhà thi đấu Tiên Sơn</p></div><div class="card"><div class="section-title"><h3>Tổng quan giải đấu</h3><a href="#" class="muted">Chi tiết</a></div><div class="overview"><div class="mini-stat"><b>14</b><small>Nội dung</small></div><div class="mini-stat"><b>256</b><small>VĐV</small></div><div class="mini-stat"><b>32</b><small>Đơn vị</small></div><div class="mini-stat"><b>128</b><small>Trận đấu</small></div></div><p class="muted">78% tiến độ giải</p><div class="progress"><i></i></div></div></div>${stats()}<div class="quick"><button data-view="create">🏆<br>Tạo giải</button><button data-view="draw">🎲<br>Bốc thăm</button><button data-view="schedule">▦<br>Lịch thi đấu</button><button data-view="results">📝<br>Nhập kết quả</button><button data-view="venues">🏟<br>Đặt sân</button><button data-view="news">📰<br>Đăng tin</button><button data-view="ai">✦<br>AI SportsVN</button></div><div class="grid grid-2"><div class="card"><div class="section-title"><h3>Giải đấu sắp diễn ra</h3><span class="muted">Xem tất cả</span></div><div class="table-wrap"><table class="table"><tr><th>Giải</th><th>Môn</th><th>Thời gian</th><th>Địa điểm</th></tr>${demo.tournaments.map(t=>`<tr><td>${t[0]}</td><td>${t[1]}</td><td>${t[2]}</td><td>${t[3]}</td></tr>`).join('')}</table></div></div><div class="card"><div class="section-title"><h3>Trận đang diễn ra</h3><span class="pill red">LIVE</span></div>${demo.matches.slice(0,2).map(m=>`<div class="notice" style="margin:8px 0"><b>${m[0]} · ${m[1]}</b><br>${m[3]} · ${m[2]}</div>`).join('')}</div></div><div class="grid grid-2" style="margin-top:14px"><div class="card"><div class="section-title"><h3>Thống kê hoạt động</h3><span class="muted">Tháng 08/2026</span></div><div style="height:180px;display:grid;align-items:end;grid-template-columns:repeat(12,1fr);gap:8px">${[25,42,58,75,92,110,85,120,135,128,160,145].map((x,i)=>`<div title="${x}" style="height:${x}px;background:linear-gradient(#0b79e8,#8fc7ff);border-radius:6px 6px 0 0"></div>`).join('')}</div></div><div class="card"><div class="section-title"><h3>Tin tức thể thao</h3><span class="muted">Mới nhất</span></div>${demo.news.map(n=>`<div class="notice" style="margin:7px 0"><b>${n[0]}</b> · ${n[1]}<br><small>${n[2]}</small></div>`).join('')}</div></div>`,'<button class="btn primary" data-view="create">＋ Tạo giải mới</button>')}
function tournaments(){return shell('Giải đấu của tôi','Mỗi tài khoản chỉ quản lý được các giải mà mình sở hữu hoặc được phân quyền',`<div class="card"><div class="toolbar" style="margin-bottom:10px"><input id="tourSearch" placeholder="Tìm tên giải..." style="padding:9px;border:1px solid var(--line);border-radius:8px;flex:1"><button class="btn primary" data-view="create">＋ Tạo giải</button></div><div class="table-wrap"><table class="table"><tr><th>Tên giải</th><th>Môn</th><th>Thời gian</th><th>Địa điểm</th><th>Trạng thái</th><th></th></tr>${demo.tournaments.map(t=>`<tr><td><b>${t[0]}</b></td><td>${t[1]}</td><td>${t[2]}</td><td>${t[3]}</td><td><span class="pill ${t[4].includes('diễn')?'green':''}">${t[4]}</span></td><td><button class="btn" data-view="draw">Quản lý</button></td></tr>`).join('')}</table></div></div>`)}
function create(){return shell('Tạo giải đấu mới','Tạo hồ sơ giải, nội dung thi đấu và mở cổng đăng ký',`<div class="card"><div class="form-grid"><div class="field"><label>Tên giải đấu *</label><input id="tourName" placeholder="Ví dụ: Giải Cầu lông SportsVN Open 2026"></div><div class="field"><label>Môn thể thao *</label><select><option>Cầu lông</option><option>Pickleball</option><option>Bóng rổ</option><option>Bóng đá</option><option>Taekwondo</option><option>Bơi</option><option>Khác</option></select></div><div class="field"><label>Ngày bắt đầu</label><input type="date" value="2026-08-24"></div><div class="field"><label>Ngày kết thúc</label><input type="date" value="2026-08-28"></div><div class="field full"><label>Địa điểm</label><input placeholder="Tên nhà thi đấu / sân / địa chỉ"></div><div class="field"><label>Phí đăng ký</label><input type="number" placeholder="0"></div><div class="field"><label>Trạng thái</label><select><option>Bản nháp</option><option>Mở đăng ký</option><option>Công khai</option></select></div><div class="field full"><label>Mô tả</label><textarea rows="5" placeholder="Điều lệ, nội dung, đối tượng, lịch..." ></textarea></div></div><div class="toolbar"><button class="btn primary" id="saveTour">Lưu giải đấu</button><button class="btn" data-view="tournaments">Hủy</button></div><div id="tourSaved" class="footer-note"></div></div>`)}
function registrations(){return shell('Đăng ký & nhận hồ sơ','Duyệt VĐV, đơn vị, nội dung và giấy tờ điện tử',`<div class="card"><div class="toolbar"><span class="pill orange">28 hồ sơ chờ duyệt</span><span class="pill green">356 đã duyệt</span><button class="btn">Xuất Excel</button></div><div class="table-wrap" style="margin-top:10px"><table class="table"><tr><th>VĐV</th><th>Đơn vị</th><th>Nội dung</th><th>Hồ sơ</th><th>Trạng thái</th><th>Thao tác</th></tr>${[['Nguyễn Văn A','Đà Nẵng','Đơn nam','Đủ','Đã duyệt'],['Trần Văn B','Quảng Nam','Đơn nam','Thiếu ảnh','Bổ sung'],['Lê Thị C','Huế','Đơn nữ','Đủ','Chờ duyệt']].map(r=>`<tr>${r.slice(0,4).map(x=>`<td>${x}</td>`).join('')}<td><span class="pill ${r[4]=='Đã duyệt'?'green':'orange'}">${r[4]}</span></td><td><button class="btn">Xem hồ sơ</button> <button class="btn">Duyệt</button></td></tr>`).join('')}</table></div></div>`)}
function drawView(){return shell('Bốc thăm thông minh','Tự động tránh cùng đơn vị ở vòng 1, hỗ trợ hạt giống, BYE và nhiều thể thức',`<div class="card"><div class="form-grid"><div class="field"><label>Thể thức</label><select id="drawFormat"><option>Loại trực tiếp</option><option>Chia bảng → Knockout</option><option>Vòng tròn</option><option>Double elimination</option><option>Swiss</option></select></div><div class="field"><label>Số suất</label><select id="drawSize"><option>8</option><option>16</option><option>32</option><option>64</option></select></div><div class="field full"><label>Danh sách hiện tại</label><div class="notice">${state.entrants.map(x=>`${x.name} — ${x.unit}`).join(' · ')}</div></div></div><div class="toolbar"><button class="btn primary" id="runDraw">🎲 Bốc thăm lại</button><button class="btn" id="exportDraw">Xuất CSV</button></div><div id="drawResult" style="margin-top:14px"></div></div>`)}
function renderBracket(){const size=+$('#drawSize').value;const p=drawFirstRound(state.entrants,size,Date.now());let html='<div class="bracket">';for(let r=0;r<Math.log2(size);r++){const count=size/2**(r+1);html+=`<div class="round"><h4>${r===0?'Vòng 1':r===Math.log2(size)-1?'Chung kết':r===Math.log2(size)-2?'Bán kết':'Vòng '+(r+1)}</h4>`;for(let i=0;i<count;i++){const a=r===0?p[i*2]?.name||'BYE':'Người thắng';const b=r===0?p[i*2+1]?.name||'BYE':'Người thắng';html+=`<div class="match"><div class="player">${a}</div><div class="vs">VS</div><div class="player">${b}</div></div>`}html+='</div>'}html+='</div>';$('#drawResult').innerHTML=html}
function schedule(){return shell('Lịch thi đấu','Điều phối giờ, sân, trọng tài và trạng thái trực tuyến',`<div class="card"><div class="toolbar"><button class="btn primary">＋ Xếp lịch tự động</button><button class="btn" data-view="venues">🏟 Chọn sân</button><button class="btn">Xuất Excel</button></div><div class="table-wrap" style="margin-top:10px"><table class="table"><tr><th>Giờ</th><th>Nội dung</th><th>Sân</th><th>Cặp đấu</th><th>Trạng thái</th></tr>${demo.matches.map(m=>`<tr>${m.slice(0,4).map(x=>`<td>${x}</td>`).join('')}<td><span class="pill ${m[4]=='LIVE'?'red':''}">${m[4]}</span></td></tr>`).join('')}</table></div></div>`)}
function venues(){return shell('Đặt sân / địa điểm thi đấu','Quản lý nhà thi đấu, sân con, sức chứa và lịch đặt theo giờ',`<div class="grid grid-3"><div class="card"><b>Cung Thể thao Tiên Sơn</b><p class="muted">8 sân · Đà Nẵng</p><span class="pill green">Đang hoạt động</span></div><div class="card"><b>Hợp Thành Phát</b><p class="muted">12 sân pickleball · An Hải</p><span class="pill green">Đang hoạt động</span></div><div class="card"><b>CLB Bơi Lặn thành phố</b><p class="muted">Bể 50m · Đà Nẵng</p><span class="pill green">Đang hoạt động</span></div></div><div class="card" style="margin-top:14px"><div class="section-title"><h3>Lịch đặt sân</h3><button class="btn primary" id="checkConflict">＋ Đặt lịch</button></div><div class="timeline">${['08:00','09:00','10:00','14:00','15:00'].map(t=>`<div><b>${t}</b></div><div><b>Sân 1</b> · Cầu lông · Đơn nam <span class="pill green">Đã giữ</span></div>`).join('')}</div><div id="conflict" class="footer-note"></div></div>`)}
function results(){return shell('Nhập kết quả','Trọng tài nhập tỷ số; hệ thống tự cập nhật bảng đấu, BXH và huy chương',`<div class="card"><div class="table-wrap"><table class="table"><tr><th>Trận</th><th>VĐV 1</th><th>Tỷ số</th><th>VĐV 2</th><th>Trạng thái</th><th></th></tr><tr><td>01</td><td>Nguyễn Văn A</td><td><input value="21 - 18" style="width:90px;padding:6px"></td><td>Trần Văn B</td><td><span class="pill green">Hoàn tất</span></td><td><button class="btn">Lưu</button></td></tr><tr><td>02</td><td>Ngọc Lan</td><td><input placeholder="2 - 1" style="width:90px;padding:6px"></td><td>Thu Hà</td><td><span class="pill orange">Chờ</span></td><td><button class="btn">Lưu</button></td></tr></table></div></div>`)}
function simple(title,desc,rows){return shell(title,desc,`<div class="card"><div class="table-wrap"><table class="table">${rows}</table></div></div>`)}
function news(){return shell('Tin tức thể thao','Biên tập, xuất bản, nguồn báo chí và nội dung do SportsVN sản xuất',`<div class="card"><div class="toolbar"><button class="btn primary">＋ Viết bài</button><button class="btn">Nhập từ nguồn / RSS</button></div><div class="notice" style="margin:12px 0">Khi sử dụng nguồn báo chí bên ngoài, hãy giữ tên nguồn, liên kết bài gốc và chỉ dùng phần nội dung được phép sử dụng.</div><div class="table-wrap"><table class="table"><tr><th>Tiêu đề</th><th>Chuyên mục</th><th>Nguồn</th><th>Trạng thái</th><th></th></tr>${demo.news.map(n=>`<tr><td><b>${n[1]}</b></td><td>${n[0]}</td><td>SportsVN</td><td><span class="pill green">Đã xuất bản</span></td><td><button class="btn">Chỉnh sửa</button></td></tr>`).join('')}</table></div></div>`)}
function ai(){return shell('AI SportsVN','Trợ lý điều hành giải đấu, biên tập tin, phân tích lịch và hỗ trợ BTC',`<div class="grid grid-2"><div class="card ai-box"><div class="chat" id="chat"><div class="bubble ai">Xin chào. Tôi là AI SportsVN. Tôi có thể giúp anh: tạo lịch thi đấu, kiểm tra xung đột sân, gợi ý thể thức bốc thăm, viết tin thể thao, tóm tắt kết quả và tạo báo cáo BTC.</div></div><form class="chat-form" id="chatForm"><input id="aiInput" placeholder="Ví dụ: Hãy xếp 16 VĐV thành 4 bảng, tránh cùng đơn vị..."><button class="btn primary">Gửi</button></form></div><div class="card"><h3>Trợ lý nhanh</h3><button class="btn" style="width:100%;margin:5px 0" data-ai="Viết bản tin 300 chữ về một giải đấu vừa kết thúc">✍ Viết tin</button><button class="btn" style="width:100%;margin:5px 0" data-ai="Kiểm tra lịch sân và tìm xung đột">🏟 Kiểm tra sân</button><button class="btn" style="width:100%;margin:5px 0" data-ai="Gợi ý thể thức cho 24 đội">🎲 Gợi ý bốc thăm</button><button class="btn" style="width:100%;margin:5px 0" data-ai="Lập báo cáo nhanh cho Ban tổ chức">📊 Lập báo cáo</button><div class="notice" style="margin-top:12px">Bản này có trợ lý cục bộ. Muốn dùng AI thật (OpenAI/Gemini), kết nối Edge Function để API key không nằm trong GitHub.</div></div></div>`)}
function accounts(){return shell('Tài khoản & phân quyền','Cho phép người khác tạo tài khoản và chỉ quản lý giải đấu của riêng họ',`<div class="grid grid-3"><div class="card"><b>Super Admin</b><p class="muted">Quản lý toàn hệ thống, gói dịch vụ, thanh toán.</p></div><div class="card"><b>Chủ giải / BTC</b><p class="muted">Tạo giải, VĐV, bốc thăm, lịch, kết quả của giải mình sở hữu.</p></div><div class="card"><b>Trọng tài / Nhân sự</b><p class="muted">Nhập kết quả và xem lịch theo quyền được cấp.</p></div></div><div class="card" style="margin-top:14px"><h3>Luồng bán phần mềm</h3><p>1. Khách đăng ký tài khoản → 2. Chọn gói → 3. Thanh toán → 4. Tạo giải → 5. Nhập hồ sơ → 6. Bốc thăm → 7. Điều phối sân → 8. Công bố kết quả.</p><button class="btn primary" data-view="payments">Thiết lập thanh toán</button></div>`)}
function payments(){return shell('Thanh toán SportsVN','Chuẩn bị bán gói quản lý giải và thu phí đăng ký ngay trên website',`<div class="grid grid-3"><div class="card"><h3>Gói Cơ bản</h3><b style="font-size:25px">299.000đ</b><p class="muted">1 giải · 100 VĐV · bốc thăm · lịch</p><button class="btn primary">Mua gói</button></div><div class="card"><h3>Gói Chuyên nghiệp</h3><b style="font-size:25px">799.000đ</b><p class="muted">5 giải · 1.000 VĐV · AI · báo cáo</p><button class="btn primary">Mua gói</button></div><div class="card"><h3>Gói Doanh nghiệp</h3><b style="font-size:25px">Liên hệ</b><p class="muted">Không giới hạn theo hợp đồng</p><a class="btn primary" href="mailto:${cfg.contact.email}">Liên hệ</a></div></div><div class="card" style="margin-top:14px"><h3>Cổng thanh toán</h3><p>Giao diện đã sẵn sàng cho VietQR/SePay/VNPay. Khóa bí mật và webhook phải đặt ở server/Edge Function, không đưa vào GitHub Pages.</p><div class="notice">Tài khoản nhận hỗ trợ: ${cfg.contact.email} · ${cfg.contact.phone} · Zalo ${cfg.contact.zalo.join(' / ')}</div></div>`)}
function settings(){return shell('Cài đặt SportsVN','Thông tin thương hiệu, liên hệ và cấu hình nền tảng',`<div class="card"><div class="form-grid"><div class="field"><label>Email</label><input value="${cfg.contact.email}"></div><div class="field"><label>Số điện thoại</label><input value="${cfg.contact.phone}"></div><div class="field"><label>Zalo 1</label><input value="${cfg.contact.zalo[0]}"></div><div class="field"><label>Zalo 2</label><input value="${cfg.contact.zalo[1]}"></div><div class="field full"><label>Website</label><input value="${cfg.siteUrl}"></div></div><button class="btn primary">Lưu cài đặt</button></div>`)}

async function render(){if(!state.user)return;$('#userName').textContent=state.user.email||'BTC Admin';const map={dashboard,tournaments,create,registrations,draw:drawView,schedule,venues,results,ranking:()=>simple('Bảng xếp hạng','Tự động cập nhật theo kết quả',`<tr><th>#</th><th>Đơn vị</th><th>HCV</th><th>HCB</th><th>HCĐ</th><th>Tổng</th></tr><tr><td>1</td><td>Quận Hải Châu</td><td>12</td><td>8</td><td>6</td><td>26</td></tr><tr><td>2</td><td>Quận Thanh Khê</td><td>8</td><td>6</td><td>4</td><td>18</td></tr>`),athletes:()=>simple('Hồ sơ vận động viên','Lưu mã VĐV, ảnh, đơn vị, lịch sử thi đấu và thành tích',`<tr><th>VĐV</th><th>Đơn vị</th><th>Môn</th><th>Thành tích</th></tr><tr><td>Nguyễn Văn A</td><td>Đà Nẵng</td><td>Cầu lông</td><td>🥇2 · 🥈1</td></tr><tr><td>Trần Văn B</td><td>Quảng Nam</td><td>Cầu lông</td><td>🥈2</td></tr>`),units:()=>simple('Đơn vị / Câu lạc bộ','Quản lý đoàn, CLB và đầu mối liên hệ',`<tr><th>Đơn vị</th><th>VĐV</th><th>Giải</th><th>Liên hệ</th></tr><tr><td>Đà Nẵng</td><td>284</td><td>26</td><td>BTC</td></tr><tr><td>Quảng Nam</td><td>163</td><td>18</td><td>BTC đoàn</td></tr>`),medals:()=>simple('Huy chương - Thành tích','Tổng hợp HCV/HCB/HCĐ theo giải, đơn vị và VĐV',`<tr><th>Đơn vị</th><th>HCV</th><th>HCB</th><th>HCĐ</th><th>Tổng</th></tr><tr><td>Đà Nẵng</td><td>52</td><td>48</td><td>61</td><td>161</td></tr>`),news,media:()=>shell('Thư viện ảnh / video','Album theo giải, ngày thi đấu, môn và VĐV',`<div class="grid grid-3">${['Khai mạc · 128 ảnh','Vòng loại · 642 ảnh','Bán kết · 311 ảnh','Chung kết · 256 ảnh','Hậu trường BTC · 98 ảnh','Video highlight · 24 video'].map(x=>`<div class="card" style="min-height:130px;background:linear-gradient(135deg,#123c78,#0a7ee0);color:#fff;display:flex;align-items:end"><b>${x}</b></div>`).join('')}</div>`),ai,accounts,payments,settings};const fn=map[state.view]||dashboard;content.innerHTML=await fn();wireView();}
function wireView(){content.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));render();}));$('#saveTour')?.addEventListener('click',()=>{$('#tourSaved').textContent='Đã tạo bản nháp: '+slugify($('#tourName').value||'giai-dau-moi')+'. Có thể kết nối Supabase để lưu thật.'});$('#runDraw')?.addEventListener('click',renderBracket);$('#exportDraw')?.addEventListener('click',()=>{const p=drawFirstRound(state.entrants,+$('#drawSize').value,Date.now());const csv='STT,VĐV,Đơn vị\n'+p.map((x,i)=>`${i+1},"${x.name}","${x.unit}"`).join('\n');const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,%EF%BB%BF'+encodeURIComponent(csv);a.download='sportsvn-boc-tham.csv';a.click();});$('#checkConflict')?.addEventListener('click',()=>{const existing=[{venue_id:'1',start:'2026-08-22T08:00',end:'2026-08-22T09:00'}];const bad=hasVenueConflict(existing,{venue_id:'1',start:'2026-08-22T08:30',end:'2026-08-22T09:30'});$('#conflict').textContent=bad?'Phát hiện xung đột: Sân 1 đang được đặt trong khoảng 08:00–09:00.':'Không có xung đột.';});$('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#aiInput').value.trim();if(!q)return;$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble me">${escapeHtml(q)}</div><div class="bubble ai">Tôi đã ghi nhận yêu cầu. Bản triển khai thật sẽ gửi yêu cầu này tới AI SportsVN qua Edge Function, sau đó trả về lịch/bản tin/báo cáo tương ứng. Hiện tại tôi có thể xử lý các mẫu bốc thăm và kiểm tra xung đột sân ngay trên trình duyệt.</div>`);$('#aiInput').value='';$('#chat').scrollTop=99999;});content.querySelectorAll('[data-ai]').forEach(b=>b.addEventListener('click',()=>{$('#aiInput').value=b.dataset.ai;$('#aiInput').focus();}));}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){state.user=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden');}});
(async()=>{state.user=await currentUser();if(state.user){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await render();}})();
