const fs = require('fs');
const assert = require('assert');
const html = fs.readFileSync(require('path').join(__dirname, '..', 'index.html'), 'utf8');
const css = fs.readFileSync(require('path').join(__dirname, '..', 'styles.css'), 'utf8');
const js = fs.readFileSync(require('path').join(__dirname, '..', 'app.js'), 'utf8');

assert.match(html, /id=["']appShell["']/);
assert.match(html, /data-section=["']Tổng quan["']/);
assert.match(html, /GIẢI CẦU LÔNG/);
assert.match(html, /TỔNG QUAN GIẢI ĐẤU/);
assert.match(html, /TRẬN ĐANG DIỄN RA/);
assert.match(html, /TIN TỨC THỂ THAO/);
assert.match(html, /LỊCH THI ĐẤU HÔM NAY/);
assert.match(html, /BẢNG XẾP HẠNG TOÀN ĐOÀN/);
assert.match(html, /THƯ VIỆN ẢNH MỚI/);
assert.match(css, /\.sidebar/);
assert.match(css, /\.dashboard-grid/);
assert.match(css, /@media/);
assert.match(js, /function drawActivityChart/);
assert.match(js, /function filterContent/);
console.log('RED/GREEN smoke test target checks loaded');
